name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build Release Binary
        run: go build -o credentialcomposer-plugin

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: credentialcomposer-plugin
          path: ./credentialcomposer-plugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: credentialcomposer-plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}